### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by k2helix**
Added the Spanish language

### CODE REVIEW

**Comment by k2helix** [comment]
By the way, when I was translating the medicine types, I thought it would be a good idea to be able to select them via a select menu instead of just typing the name. I didn't know it was possible to do that before translating the file.

**Comment by pewaru-333** [comment]
Thank you!

Now I am redesigning medicine information screen, so this string.xml is outdated. The update will be rolled at this weekends. In a version I will include translations and add Spanish to language picker in settings.

**Comment by k2helix** [comment]
I see, thanks! When you roll out the update, I will edit the strings.xml file.

**Comment by k2helix** [comment]
@pewaru-333 I've finished updating the strings.xml file. Hope it is useful

**Review by pewaru-333 — APPROVED** [review]

**Comment by pewaru-333** [comment]
Thank you. Translations will be added in next update.

**Pull request merged**
